services:

  mariadb:
    build: ${INCEPTION_PATH}/srcs/requirements/mariadb
    container_name: ${MDB_CONTAINER_NAME}
    image: ${MDB_IMAGE_NAME}
    ports:
      - ${MDB_PORT}:${MDB_PORT}
    volumes:
      - ${SECRETS_PATH}/mariadb:/secrets/mariadb:ro
      - inception_mariadb_volume:/var/lib/mysql
    env_file:
      - ${ENV_PATH}
    networks:
      - ${NETWORK_NAME}
    restart: always

  wordpress:
    build:
      context: ${INCEPTION_PATH}/srcs/requirements/wordpress
      dockerfile: Dockerfile
      args:
        - WP_PHP_USER=${WP_PHP_USER}
        - WP_PHP_GROUP=${WP_PHP_GROUP}
    container_name: ${WP_CONTAINER_NAME}
    image: ${WP_IMAGE_NAME}
    ports:
      - ${WP_PORT}:${WP_PORT}
    volumes:
      - ${SECRETS_PATH}/mariadb/mdb_user_pwd.txt:/secrets/mariadb/mdb_user_pwd.txt:ro
      - ${SECRETS_PATH}/wordpress:/secrets/wordpress:ro
      - inception_wordpress_volume:/var/www/html
    env_file:
      - ${ENV_PATH}
    networks:
      - ${NETWORK_NAME}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD-SHELL", "echo 'WordPress is running'"]
      interval: 20s
      timeout: 30s
      retries: 50
    restart: always

  nginx:
    build: ${INCEPTION_PATH}/srcs/requirements/nginx
    container_name: ${NGINX_CONTAINER_NAME}
    image: ${NGINX_IMAGE_NAME}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ${SECRETS_PATH}/ssl:/etc/nginx/ssl:ro
      - inception_wordpress_volume:/var/www/html
    env_file:
      - ${ENV_PATH}
    networks:
      - ${NETWORK_NAME}
    depends_on:
      wordpress:
        condition: service_healthy
    restart: always

volumes:
  inception_mariadb_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${MDB_VOLUME}
    name: ${MDB_VOLUME_NAME}

  inception_wordpress_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${WP_VOLUME}
    name: ${WP_VOLUME_NAME}

networks:
  inception:
    name: ${NETWORK_NAME}
    driver: bridge
